# Generated by Django 4.2.2 on 2023-07-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fruitstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fruitstore",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="fruitstore",
            name="phoneNumber",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="FruitMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruitMenuList",
                        to="fruitstore.fruitstore",
                    ),
                ),
            ],
        ),
    ]
